language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
sudo: false
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: ojJPFMfgRrUIAfeS5BfonnMydPPJEG6hnbb3TGsb4RIi9lGNMBjJ0IvzVJfWFcdwYkphXt/TQA3t0iwomtZYG+pWb1/WsXUP76kNQRquqbhcUuLnbv7b2fZgD4VzRl7xMxxFU1+aoP1sS07hvUTVvUP0da7ePmEapaTX4FXosc444hg18pItXbLkUWWxHS22Ec+DSYx8248ppmbrq8998eAyfrzaOSMx8/U73/yzz4I/jjA2ndZtSn8VBTVH8SfxSSFe8lFfe9fddZMNtumw1xUoc0SKD3gAGXVl9MsqGXl+SO5mkdAgl72MYvr6O59lSIPYL+CqMldsPeI5gG3fERldt/lqsTflZZcoi8snIu/CHayf/c/WBgjVRXp5htbxglvzvkZS0Gca41X9blRJmIOOZMw28NjXs152uAc6zG9mHqyTcKPu4QAZ6wLuCXFIOPNst1Zth0XRj/67pQWp2xDmB9nP3z3jaRQEA54h2seeZbnY0sHUv1cJnRS6LcC8ptJ48lm25XE6TMge2XTr1hX6E2dfcg4KRQGB1pD6b7I9+iEyTCAWXOG3IjNQTIkvEXnNyJrv4IyEdIhW3U6XpkHEGGidyNmSmLbWAG0EEm+oND1m7zsOtRQbvorQrd1eFIPzE1Az+QXNJ02VtUpjGeeNLd5esOMGhm4aiIUTpYU=
  on:
    tags: true
    repo: flowbased/flowtrace
